title: Tim Truty
subtitle: Software engineer and research specialist
description: >- # this means to ignore newlines until "baseurl:"
  Connecting technology and people.

url: "" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    # - text: Gallery
    #   url: /gallery
    # - text: Shop
    #   url : /shop
    - text: Contact Me
      url : /contact
    # - text: Styleguide
    #   url: /styleguide
    # - text: Get Started
    #   url: /get-started

# Edit these details

author_logo: profile.png
author: Tim Truty
author_bio: A researcher with a passion for new tech and connecting people with devices. Technology advances to help people and the world. All things tech interest me as well as 90s pop punk and some hacky sack. All the views expressed here are solely mine and do not represent any organization. 
author_email: "ttruty@gmail.com"
author_location: Minneapolis
author_website_url: "http://timtruty.com"
typewrite-text: Hack the planet.

author_work_experiences:
            - company_name: Minneapolis Adaptive Design & Engineering Program
              company_logo: MADE_LOGO.jpg
              company_url: https://www.va.gov/minneapolis-health-care/programs/minneapolis-adaptive-design-engineering-program/
              designation: Research Computer Scientist
              description: Software design, development, and deployment to support adaptive technology. 
              visibility: true
            - company_name: Northwestern University, HABits Lab
              company_logo: Habits.jpg
              company_url: https://thehabitslab.com
              designation: Software Engineer
              description: Develop software to help with behavioral research using wearables and machine learning
              visibility: true
            - company_name: Rush Alzheimer's Disease Center
              company_logo: radc.png
              company_url: https://www.rushu.rush.edu/research/departmental-research/rush-alzheimers-disease-center
              designation: Project Coordinator
              description: Technology and device specialist for longitudinal aging studies
              visibility: true
            

author_education_details:
              - college_logo: illinois-tech.svg
                college_name: Illinois Institute of Technology
                college_url: https://www.iit.edu/
                college_degree: ITM, Digital Systems & Embedded Devices
                description: Masters Applied Technology
                visibility: true
              - college_logo: isu.png
                college_name: Illinois State University
                college_url: https://illinoisstate.edu/
                college_degree: Psychology, Minor- Gerontology
                description: Bachelor's
                visibility: true

author_project_details:
              - project_thumbnail: bmbg-logo.jpg
                project_title: Codememes Project
                project_description: Codenames game with meme and gifs with web hooks
                project_url: https://codememes-603998739955.us-central1.run.app
                visibility: true
              - project_thumbnail: youtube.jpeg
                project_title: Youtube channel
                project_description: Tim's youtube channel to demo projects
                project_url: https://www.youtube.com/user/truty
                visibility: true
              - project_thumbnail: ethereum-coin.jpeg
                project_title: IsCryptoDead Blog
                project_description: A blog Tim created as a joke, it turned serious
                project_url: https://iscryptodead.com
                visibility: true
              - project_thumbnail: settld-it.png
                project_title: Settld-it
                project_description: A project to help people settle disputes
                project_url: https://settldit-app.web.app
                visibility: true
              
              

# social links
twitter_username: trutylicious
github_username:  ttruty
facebook_username: tim.truty
linkedin_username: timothy-truty-707a4659
youtube_username: ttruty
# behance_username: johndoe
instagram_username: trutytime
# medium_username: johndoe
# telegram_username: johndoe
# dribbble_username: johndoe
# flickr_username: johndoe

#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: sujay-kundu
hyvor_talk_website_id: 991

# wakatime username (coding activity)
wakatime_username: ttruty

# mailchimp embedded form url (newsletter):
# mailchimp_form_url: https://sujaykundu.us10.list-manage.com/subscribe/post?u=50bab1c85eae24ecfb0f68361&amp;id=3a2dd721d0

# formspree (contact form)
formspree_email: ttruty@gmail.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# algolia search
algolia:
  application_id: 9G6SN6S2KI
  index_name: ttruty_BLOG # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 939d81d532ff3a4f6d56e9fa3bbcefe3

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
# collections:
#  - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
